### ISSUE TITLE
it's not possible to turn off http server

### ISSUE THREAD

**Issue by DEvil0000** [klarna/brucke#26]

**Comment by id** [comment]
Why is it an issue?

**Comment by DEvil0000** [comment]
I am trying to change all the config values while it is running. Restarting the whole BeamVM is not an option because this would generate an alarm for an operator.

Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: Ivan Dyachkov <notifications@github.com> 
Datum: 06.07.2017  22:16  (GMT+01:00) 
An: klarna/brucke <brucke@noreply.github.com> 
Cc: "A. Binzxxxxxx" <alexander@binzberger.de>, Author <author@noreply.github.com> 
Betreff: Re: [klarna/brucke] it's not possible to turn off http server (#26) 

Why is it an issue?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/klarna/brucke","title":"klarna/brucke","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/klarna/brucke"}},"updates":{"snippets":[{"icon":"PERSON","message":"@id in #26: Why is it an issue?"}],"action":{"name":"View Issue","url":"https://github.com/klarna/brucke/issues/26#issuecomment-313507120"}}}

**Comment by DEvil0000** [comment]
merged
