### ISSUE TITLE
should the consumer_group_id be within the consumer config instead of routes? and configuration documentation

### ISSUE THREAD

**Issue by DEvil0000** [klarna/brucke#33]
Thanks for adding this (de62d7d) otherwise I would have added it now.

I was also thinking about adding it to the routes as a config value but then I was thinking its cunsumer client config and should be there. What do you think about moving the group_id config to the consumer client config?

BTW you missed to document this important feature ;)

**Comment by zmstone** [comment]
The way consumer group implemented in `brod` is detached from client or consumer config.
It is more of a `brod_group_member`'s config, hence IMO, putting it as a route config makes better sense.

I will update README.

**Comment by DEvil0000** [comment]
Talking about readme:
It is also not documented how to set begin_offset/offset reset strategy for consumers and producer compression method.

**Comment by zmstone** [comment]
Will add that too. Thanks.

**Comment by zmstone** [comment]
@DEvil0000 Does PR #34 look good to you ?

**Comment by DEvil0000** [comment]
maybe I should open a new ticket for this but its related for me:
This query versioning (query_api_versions) thing should also be configurable I think.
https://github.com/klarna/brod#working-with-kafka-09x-or-earlier

**Comment by zmstone** [comment]
'Documented' `query_api_versions` in README.
However, brucke was using brod `2.5.0`, `query_api_versions` was added to brod `3.2.0`,
so I had to upgrade brod for this PR.
